# Generated by Django 4.1.7 on 2023-06-27 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggApp', '0001_initial'),
    ]

    operations = [
    ]
