# Generated by Django 4.2.2 on 2023-06-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggApp', '0002_students'),
    ]

    operations = [
    ]
