# Generated by Django 4.2.2 on 2023-06-27 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggApp', '0004_initial'),
    ]

    operations = [
    ]
