# Generated by Django 4.2.2 on 2023-08-04 13:59

# refer https://blog.logrocket.com/using-react-django-create-app-tutorial/

from django.db import migrations


def create_data(apps, schema_editor):
        Users = apps.get_model('userAuth', 'Users')
        # users ^ is user model
        Users(name = "abc", email = "abc@gmail.com", password = "abc", gender = "M").save()

class Migration(migrations.Migration):
    
    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
