# Generated by Django 4.2.2 on 2023-08-04 14:18

from django.db import migrations

def create_data(apps, schema_editor):
        Users = apps.get_model('userAuth', 'Users')
        # users ^ is user model
        Users(name = "abc", email = "abc@gmail.com", password = "abc", gender = "M").save()

class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0003_userAuth2'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
