# Generated by Django 4.2.2 on 2023-08-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0004_userAuth3'),
    ]

    operations = [
    ]
